camera_index: 
  front: 0
  rear: 10
  left: 10
  right: 10 
# 10 is Disable
resolution:
  height: 400
  width: 600

base_directory: video
maximum_video_time: 15
format_video:
  "AUTONXT_%Y%m%d_%H%M%S"