name: Auto Build and Push Docker Image

on:
  push:   
    branches:
      - "**" 
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./camera_app
          file: ./camera_app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/camera_app:latest
            ghcr.io/${{ github.repository_owner }}/camera_app:${{ github.sha }}
